### ISSUE TITLE
[Media] Improve file upload validation

### ISSUE THREAD

**Issue by duylv27** [nashtech-garage/yas#1025]
We are using the following API for uploading the file. By changing the file extension (change a PDF file extension to `.pnj`), we can upload the file successfully.
```
POST: /media/medias
``` 

Ideally, we will define 2 parts:
- Create an annotation named `@AllowTypes(types= {MediaType.IMAGE_JPEG, MediaType.IMAGE_GIF, MediaType.IMAGE_PNJ}` which will be annotated on the `MultipartFile` parameter type.
- Define validation logic to validate the `MultipartFile` parameter type when the REST method is invoked.

**_Sample code:_**
```java
public record MediaPostVm(
              String caption, 
              @AllowTypes(types= {
                            MediaType.IMAGE_JPEG, 
                            MediaType.IMAGE_GIF, 
                            MediaType.IMAGE_PNJ} @NotNull MultipartFile multipartFile, 
              String fileNameOverride) {
}
```

**Comment by VanCongBang** [comment]
**Added test case for when the file is still within allowed types, 
but does not contain real image content.**
