### ISSUE TITLE
[Add to cart] The quantity doesn't increase if the same product code

### ISSUE THREAD

**Issue by chinhduongthi** [nashtech-garage/yas#1037]
The quantity doesn't increase if the same product code when we click button [add to cart]

**Comment by duylv27** [comment]
**_Description:_** 
When a product is already in the cart, clicking the **Add to cart** button on the **Product Detail Page** does not update the cart quantity.

**_Current behavior:_**
- The cart quantity doesn't increase.
- The cart item for the corresponding product doesn't update its quantity.

_**Expected:**_
- The cart quantity should increase by 1.
- The cart item for the corresponding product should increment its quantity by 1.

![image](https://github.com/user-attachments/assets/e5f6a340-97c0-4afe-930a-56a106d5576e)
