### ISSUE TITLE
[BACKOFFICE] [Bugs] Product Variations

### ISSUE THREAD

**Issue by VanCongBang** [nashtech-garage/yas#1064]
### 1. After select product in homepage, product's images are showing incorrectly with product variations.
![image](https://github.com/user-attachments/assets/0db42721-df88-448b-981e-c5cc81a63839)

### 2. Product variations have been added with images, but they are not showing in the Storefront.
![image](https://github.com/user-attachments/assets/bbf4e40e-6f84-4663-9772-60877895d262)

### 3. After removing product variations, they are still present in the Storefront.
![image](https://github.com/user-attachments/assets/6717d844-1cec-400a-b19c-37cb53f1f02d)

### 4. When Color Variation is chosen after Storage Variation, the product title and image do not change; they remain stuck on Storage.
![image](https://github.com/user-attachments/assets/94f62bd2-af08-4976-befa-ab36ed30e718)

**Comment by VanCongBang** [comment]
### 5. Inconsistent variant selection while adding multiple Product Variant type: Color, Storage,.. 
 
![image](https://github.com/user-attachments/assets/4b17576c-375c-46be-be04-63c64ae49bac)

**Comment by nashtech-tuannguyenhuu1** [comment]
![image](https://github.com/user-attachments/assets/d62578ed-b526-48ab-b9c0-d66e3855d832)

![image](https://github.com/user-attachments/assets/c21e47c1-2ff0-4304-bf13-8d636ea2c093)

It's OK.
