### ISSUE TITLE
[storefront] Allow customers to select items to checkout

### ISSUE THREAD

**Issue by thiennn** [nashtech-garage/yas#1083]
In the shopping cart, add checkbox on the left of each items. Allow customer to select items they want to checkout. 
It should check all by default?

**Comment by mochacr0** [comment]
Hi @thiennn, I’m concerned that automatically selecting all items by default could cause confusion or lead to unintentional purchases. 

I’ve reviewed several e-commerce sites, and they typically don’t select all items by default. Instead, they provide a 'Select All' option for users who want that convenience. What do you think about following this approach?

![image](https://github.com/user-attachments/assets/e66ccb79-cf33-408b-bd1c-7f9eb13172e3)

![image](https://github.com/user-attachments/assets/10b74f56-d2a6-40ed-8627-c903ccb52313)

**Comment by thiennn** [comment]
Agree, so don't checked all by default.
