### ISSUE TITLE
Remove ProductOptionValue table

### ISSUE THREAD

**Issue by NhatTranMinh15** [nashtech-garage/yas#1129]
Currently, ProductOptionValue table hold the values for product option selection in storefront:
![image](https://github.com/user-attachments/assets/ce2673b0-29c2-48d0-9f5b-2938a93ccc83)
![image](https://github.com/user-attachments/assets/68531379-43e0-4475-b820-d68b39f05026)
But these values are also stored in ProductOptionCombination table:
![image](https://github.com/user-attachments/assets/f39149ba-0fc6-4b04-8bc4-2426dc8fb09a)
CRUD operation can be done on ProductOptionCombination which have the same result as done on ProductOptionValue.
ProductOptionValue table also have some problems:
1. Duplicated values: https://github.com/nashtech-garage/yas/issues/978
2. Data sync on product variation deletion: When delete a product variation, each value in ProductOptionValue table that belong to the variation must be evaluated to be kept or deleted base on other variations option value. A value can only be deleted if it is not used by any other variation.
Thus, ProductOptionValue should be remove and replace by ProductOptionCombination

**Comment by minhtridn2001** [comment]
As discussed, the current behavior is by design, so no changes are needed.
