### ISSUE TITLE
[Storefront][Product] - Show Product Color Options as colored label instead text name label

### ISSUE THREAD

**Issue by VanCongBang** [nashtech-garage/yas#1183]
**Currently**, product color is displayed by name (e.g.: Blue, Black, Green...)
**Expected**: The product color should be displayed as a colored label instead of a text name.

Example:
<img width="954" alt="image" src="https://github.com/user-attachments/assets/0def59c1-b032-4842-86e9-cf59ed5f82dc">

![image](https://github.com/user-attachments/assets/6113b840-b80b-4721-b5f3-8d9fc9cb379d)

**Comment by VanCongBang** [comment]
Currently blocked by bugs found in this feature
https://github.com/nashtech-garage/yas/issues/1201

Need to resolve https://github.com/nashtech-garage/yas/issues/1201 before merge

**Comment by khanhduzz** [comment]
- Update Option Value UI when create/update product

![image](https://github.com/user-attachments/assets/5418fa1b-bd9c-4259-9d70-07349c0d6944)
