### ISSUE TITLE
[backoffice] product disappear from list products after performing edit this product

### ISSUE THREAD

**Issue by khoahd7621** [nashtech-garage/yas#446]

**Comment by toannguyenk** [comment]
Can you add detail description ?
best idea to add step by step to reproduce

**Comment by khoahd7621** [comment]
- At backoffice, after clicking edit a product, you'll be navigated to product lists and can't see this product anymore.
But you still can see this product with changed information in storefront.
- Right now I don't have any clue about this issue. Anybody hands on this issue should make an effort to figure out why it happens.
