### ISSUE TITLE
[backoffice] Cannot create product when product have variant

### ISSUE THREAD

**Issue by khoahd7621** [nashtech-garage/yas#470]
Stack trace for this error:

![image](https://user-images.githubusercontent.com/77594830/226325722-d7e3ae7f-d582-42e4-983b-3fcfe600929a.png)

**Comment by thiennn** [comment]
Actually we should remove the column remaining_quantity, and replace by the stockTrackingEnabled (boolean). And all the variations (if any) should inherit this value from parent product
