### ISSUE TITLE
[storefront] Product detail page: rating should be rendered in client side

### ISSUE THREAD

**Issue by thiennn** [nashtech-garage/yas#482]
As rating information don't need optimize for SEO, it should be fetch and render in client side to optimize performance

Rating components should be separate to it own module not in catalog

**Comment by LEHOANGGLAM** [comment]
Our Rating list was already render in client side, The average-star is render in service because each "product detail page" need to show average-star. Thus, i think we just should separate rating module to it own module in this issue. Thanks

**Comment by LEHOANGGLAM** [comment]
done
