### ISSUE TITLE
Remove convert JWT code 

### ISSUE THREAD

**Issue by nashtech-minhtran** [nashtech-garage/yas#556]
Since the new update from Spring Boot and Keycloak, we don't have to use the below block of code to map the role from Keycloak to SpringBoot Authentication. Therefore, the security config should be updated like this:

- Our old security config:

![code](https://user-images.githubusercontent.com/98141505/229017270-6fee390f-9a49-4cd4-bb79-e65b8bc80db4.png)

- New security config example:
![image](https://user-images.githubusercontent.com/98141505/229017416-3750d5a2-9d72-442f-9724-c72f729d1a7e.png)
+ After decorate securityConfig class with annotation @EnableMethodSecurity, we can simple decorate API method with @PreAuthorize in controller like this
![image](https://user-images.githubusercontent.com/98141505/229017560-91359a79-cd54-4253-9fff-e5f91cad0994.png)

**Comment by khoahd7621** [comment]
Thanks for your suggestion. Let me try.

**Comment by nashtech-minhtran** [comment]
My mistake, I've not restarted the server when removing the JwtConverter code. You can close this issue, thank you and sorry for taking your time.

**Comment by khoahd7621** [comment]
So we still need JwtConverter, is it right, @nashtech-minhtran?

**Comment by nashtech-minhtran** [comment]
yep, we still need that to authorize the user. However, we can still decorate the @EnableMethodSecurity for using @PreAuthorize in controller. After that we can then remove .requestMatchers().hasRole() in filterChain

**Comment by khoahd7621** [comment]
Okay, thank you. Nothing will change after closing this issue.
