### ISSUE TITLE
[elasticsearch] perform full text search for a list of product

### ISSUE THREAD

**Issue by lnghia** [nashtech-garage/yas#571]
Perform a full text search with typed in keyword and selected filters, also we might need to add aggregation query so that we can do a quick count to see how many products there are that match the query in each filter option. 
For further info, check [elasticsearch aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html)
Example of how aggregation might look like (check the filter bar, each option has a number with it stands for the number of product with that attribute matching the query) [example repo](https://github.com/spinscale/elasticsearch-ecommerce-search-app)

![image](https://user-images.githubusercontent.com/43461631/229391419-46b214c1-7225-4ea6-829e-0ca7f9c41775.png)

**Comment by khoahd7621** [comment]
Thanks for your detailed description.
