### ISSUE TITLE
use healthcheck and depends_on instead of wait-for-it

### ISSUE THREAD

**Issue by thiennn** [nashtech-garage/yas#641]

**Comment by khoahd7621** [comment]
Currently, our application uses Keycloak version 21, and based on [Keycloak 21 released document](https://www.keycloak.org/2023/02/keycloak-2100-released.html), `curl` and `other CLI tools` have been removed.

YAS requires Identity service (using Keycloak) needs to start successfully before backoffice-bff and storefront-bff services can run. To ensure that, we need to set up healthcheck for Identity container.

Based on [Docker compose document](https://docs.docker.com/compose/compose-file/compose-file-v3/) they use Curl in healthcheck to check container starts successfully or not. With this change of default Keycloak image, we can't implement it now and in the future.

Right now, there are two solutions:
- One is to build a custom Keycloak image, add `curl` manually, run this Identity based on this custom image and we can implement healthcheck
- Two is to keep using wait-for-it.

**Comment by khoahd7621** [comment]
Currently, our application uses Keycloak version 21, and based on [Keycloak 21 released document](https://www.keycloak.org/2023/02/keycloak-2100-released.html), `curl` and `other CLI tools` have been removed.

YAS requires Identity service (using Keycloak) needs to start successfully before backoffice-bff and storefront-bff services can run. To ensure that when using this approach, we need to set up healthcheck for Identity container.

Based on [Docker compose document](https://docs.docker.com/compose/compose-file/compose-file-v3/) they use Curl in healthcheck to check container starts successfully or not. With this change of default Keycloak image, we can't implement it now and maybe in the future.

Mr. @thiennn suggests two solutions:
- One is to build a custom Keycloak image, add `curl` manually, run container Identity based on this image and we can implement healthcheck
- Two is to keep using wait-for-it.

And we decide to keep using wait-for-it. 😁
