### ISSUE TITLE
Investigate and fix unit test result report 

### ISSUE THREAD

**Issue by thiennn** [nashtech-garage/yas#692]
Some workflow doesn't show unit result report. For example https://github.com/nashtech-garage/yas/actions/runs/5109422529

But others do: https://github.com/nashtech-garage/yas/actions/runs/4728321212

**Comment by tanhaok** [comment]
I think it has shown up unit result but in another ci https://github.com/nashtech-garage/yas/runs/13827799338.
This issue is similar to this issue https://github.com/dorny/test-reporter/issues/67.

**Comment by khoahd7621** [comment]
I think these workflows all show unit test result reports. But we export them with the same name `Unit-Test-Results` so they override each other.
Let me try to rename each of them with a specific name.

**Comment by khoahd7621** [comment]
After set specific name for each report, they all show but centralize into the first ci:

![image](https://github.com/nashtech-garage/yas/assets/77594830/44c8a811-a472-405d-b18d-140cbcdb56ec)

**Comment by thiennn** [comment]
:joy: then we should investigate further

**Comment by thiennn** [comment]
"Check Runs are created for specific commit SHA. It's not possible to specify under which workflow test report should belong if more workflows are running for the same SHA. Thanks to this GitHub "feature" it's possible your test report will appear in an unexpected place in GitHub UI"

It seem that we can not do any thing further
