### ISSUE TITLE
[Observablity] Develop the Grafana dashboard for Observabilty

### ISSUE THREAD

**Issue by loinguyen-nt** [nashtech-garage/yas#730]
To provide later #TODO

**Comment by thiennn** [comment]
Build a opinionated Grafana dashboard contains typical metric for java application, combine with logs and traces

**Comment by nashtech-huyphamphu** [comment]
Dear anh @thiennn and @khanhtranduy,
Please help me to review below PR:
https://github.com/nashtech-garage/yas/pull/831
![image](https://github.com/user-attachments/assets/737ed447-fe77-4fa5-91f0-313f60cbb483)
![image](https://github.com/user-attachments/assets/dbb33acc-0ec3-4cc8-96df-b0ddd59ce391)
![image](https://github.com/user-attachments/assets/f0c2f1e9-0cf4-4e0e-a949-ae7cfe801871)
![image](https://github.com/user-attachments/assets/c3af18cc-f9fa-48ba-ae6e-dbc90240b76c)
![image](https://github.com/user-attachments/assets/0bce120f-d741-4745-9e87-659f488b79bf)
![image](https://github.com/user-attachments/assets/ad5da30f-ed9e-43ce-8b7b-e3e65001b1cb)

Thanks

**Comment by nashtech-huyphamphu** [comment]
Dear anh @thiennn and anh @khanhtranduy ,
Please help me to review below MR:
https://github.com/nashtech-garage/yas/pull/839

Thanks and regards,
Vu huy

**Comment by nashtech-huyphamphu** [comment]
Dear anh @thiennn and anh @khanhtranduy ,
I have modified Dashboard as your comment.
Please help me to review below MR: 
https://github.com/nashtech-garage/yas/pull/843

Thanks and regards,
Vu huy
