### ISSUE TITLE
[Shopping Cart] The product image display incorrectly when a product have multiple variations

### ISSUE THREAD

**Issue by thiennn** [nashtech-garage/yas#811]
![image](https://github.com/user-attachments/assets/f921ec54-db02-46b6-bc31-cafa0212315c)

**Comment by thiennn** [comment]
#810

**Comment by nashtech-tuannguyenhuu1** [comment]
Hi Mr. @thiennn,
Cause: Product variant has no thumbnail yet
Solution: can be solved by selecting thumbnails for product variant.
![image](https://github.com/user-attachments/assets/26a95306-afbb-4bcd-898b-6b6202b34a86)

Please help me close this issue.
Thanks
