### ISSUE TITLE
[Backoffice] Description & Specification Product fields randomly cleared to blank even successfully created

### ISSUE THREAD

**Issue by VanCongBang** [nashtech-garage/yas#827]
Created product "Iphone 15 Pro" successfully => Edit Product still see 2 fields:  Description & Specification with shown content here

![image](https://github.com/user-attachments/assets/3dff2775-ab2c-4aac-a820-0e7da44ffb90)

But when edit other products , and back to edit "Iphone 15 Pro" => it cleared content to blank 

![image](https://github.com/user-attachments/assets/ada7d41f-6c1b-4729-8e3d-e0facf804713)

**Comment by nashtech-tuannguyenhuu1** [comment]
![Uploading image.png…]()
