### ISSUE TITLE
[Backoffice] Throw generic error when create/edit product variant and unnecessary redirect to homepage

### ISSUE THREAD

**Issue by VanCongBang** [nashtech-garage/yas#885]
In backoffice, when creating new Product or editing Product, when try to add new product variation, it has checked for GTIN & SKU exist in database or not. 
![image](https://github.com/user-attachments/assets/d9aae089-6e1a-4a5a-8c83-50686f9be417)

But instead of stay in page and notify user, it redirect to home page, and throw generic error " UPDATE FAILED " -> make user don't know which error caused this problem.
![image](https://github.com/user-attachments/assets/63f1d540-88bc-4d8b-bfef-d0b2f70e6b9a)

**Expect: Throw detail error that API respone , and stay in create/edit page and let user continue modify.**

**Comment by nashtech-tuannguyenhuu1** [comment]
![image](https://github.com/user-attachments/assets/c25cb1f9-2cfc-4476-9796-ac802f59d9ed)
![image](https://github.com/user-attachments/assets/4c7d4696-2580-41fe-be26-769434ebd163)
