### ISSUE TITLE
[Promotion] Check negative discount percentage and end date of promotion can not be before start date

### ISSUE THREAD

**Issue by HnKnA** [nashtech-garage/yas#890]
### Problem
- Currently, promotion can be created with negative value of discountPercentage or discountAmount.
- Currently, promotion can be created with end date place before start date. 

### How to resolve
- Add min(and max) value of _discountPercentage_ and _discountAmount_.
- Check for invalid _Date Range_

**Comment by hnd14** [comment]
On the same note, maybe discountPercentage should also be capped at 100.
