### ISSUE TITLE
[Bug][Rating] Get rating in back office failed if parameters not present 

### ISSUE THREAD

**Issue by NhatTranMinh15** [nashtech-garage/yas#917]
The URL GET /backoffice/ratings returns an error 500 when the request is sent without the 'createdFrom' and/or 'createdTo' parameters.

![image](https://github.com/user-attachments/assets/341d73b3-b9a5-4a9a-b785-c2149e15f6de)

**Expected**
The endpoint returns list of all ratings if no parameter is presented.

**Comment by adnan1605** [comment]
Anyone contributing to this issue.

**Comment by NhatTranMinh15** [comment]
Bug Resolved

![image](https://github.com/user-attachments/assets/a0c9f6cf-b511-42a0-a05b-03efc835bb74)
