### ISSUE TITLE
[Event-Streaming] Enhance Payment Flow

### ISSUE THREAD

**Issue by LEHOANGGLAM** [nashtech-garage/yas#996]
Current payment with Paypal:
![image](https://github.com/user-attachments/assets/88d2613b-92b2-475c-89fc-5f0aa801ea1d)

Update new flow:
![image](https://github.com/user-attachments/assets/388a742e-1ffc-44b7-abcf-59d907881410)

**Comment by LEHOANGGLAM** [comment]
Hi @thiennn , @khanhtrand, @nashtech-bangnguyenl Could you review my new flow to process payment with paypal? Thanks

**Comment by thiennn** [comment]
I think we might not need the message system here. It seems over complicated.

**Comment by LEHOANGGLAM** [comment]
thanks @thiennn , the issue https://github.com/nashtech-garage/yas/issues/1003 make more sense and simple
